$axure.loadCurrentPage({
  "url":"用户未拆红包或未塞满过期，24小时返回金额.html",
  "generationDate":new Date(1464855302812.43),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9c7ecb38aace46c2b11576a0ce3b6ca1",
    "type":"Axure:Page",
    "name":"用户未拆红包或未塞满过期，24小时返回金额",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"df5c4212a9744144a2016e9fbf897a71",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":679,
              "y":90},
            "size":{
              "width":320,
              "height":570},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f284cc7071d94d6d826f4a2038a9b153",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":679,
                  "y":90},
                "size":{
                  "width":320,
                  "height":570},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】群会话入口/u24.png"}},
{
          "id":"48f7f0d62c3e443c89659c9085ec8286",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":680,
              "y":91},
            "size":{
              "width":318,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2bb81627866b489fac4d75d797d52025",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":680,
                  "y":91},
                "size":{
                  "width":318,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户未拆红包或未塞满过期，24小时返回金额/u2.png"}},
{
          "id":"6a16672b523c4d4eb8ee86d685c3c496",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF1F1F1},
            "location":{
              "x":680,
              "y":200},
            "size":{
              "width":318,
              "height":408},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0bf90456b26549e495e65fb9f15692d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF1F1F1},
                "location":{
                  "x":680,
                  "y":200},
                "size":{
                  "width":318,
                  "height":408},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户未拆红包或未塞满过期，24小时返回金额/u4.png"}},
{
          "id":"b0042e409ac442009d08a2c379125990",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":679,
              "y":64},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26a99cc7d1fd44e8b6267582e65283bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":679,
                  "y":64},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dbc035f9773f436d8bea5f0752abae7c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":790,
              "y":110},
            "size":{
              "width":109,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1de9a5c1234f4c47b2b336881750fa73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":790,
                  "y":110},
                "size":{
                  "width":109,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户未拆红包或未塞满过期，24小时返回金额/u8.png"}},
{
          "id":"3dd0db31e60247a29d4431d32590426f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":802,
              "y":118},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffd2db5f1d76464fa7aac04d6a42e0f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":802,
                  "y":118},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e52db3709bf147d3bcc7a9027896312c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":60,
              "y":90},
            "size":{
              "width":320,
              "height":570},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d13d8741ec864ba9947ca8519e9757cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":60,
                  "y":90},
                "size":{
                  "width":320,
                  "height":570},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】群会话入口/u24.png"}},
{
          "id":"3397d16800ad43bba8bce1cb9fe0230d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":91},
            "size":{
              "width":318,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b63da355ae194950a619427ee3d8af94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":61,
                  "y":91},
                "size":{
                  "width":318,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户未拆红包或未塞满过期，24小时返回金额/u2.png"}},
{
          "id":"d747245a99f74ca2ae8fea9fe3afdbb2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF1F1F1},
            "location":{
              "x":61,
              "y":200},
            "size":{
              "width":318,
              "height":408},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d41afc32bc34a739ae7af6600cd7a3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF1F1F1},
                "location":{
                  "x":61,
                  "y":200},
                "size":{
                  "width":318,
                  "height":408},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户未拆红包或未塞满过期，24小时返回金额/u4.png"}},
{
          "id":"723398fdf0d34bc68931f4dcce807909",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":74,
              "y":210},
            "size":{
              "width":294,
              "height":300},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"14"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99b71c13229d49ccba80e3a9754b82b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":74,
                  "y":210},
                "size":{
                  "width":294,
                  "height":300},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"14"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户未拆红包或未塞满过期，24小时返回金额/u18.png"}},
{
          "id":"ac53fa83fe3243368b0c02afc1481882",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":90,
              "y":231},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea35118be435495692e062faa7aa6918",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":90,
                  "y":231},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"79cc4899aa554587a9a3431147da9c71",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":90,
              "y":254},
            "size":{
              "width":50,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50c92869adc544b4946cfe9a7ad4acce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":90,
                  "y":254},
                "size":{
                  "width":50,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c40fc06aeebd4993b28e359f7c2f3eb7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":344},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd3547fb094c48d4bb6dfdd9248b5082",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":344},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e2950009334643ab85d429b32a3fe73e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":373},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1a66088ec3449eaafddf569e8513884",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":373},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"28d432572e314151b2606fe3cf3f5665",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":404},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7821a2f75494643ad9a24f142b8c474",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":404},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2ae06a8515254cffaa9c34006832ecd3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":90,
              "y":465},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ab58d1130664f388c627907161851cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":90,
                  "y":465},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab7da1166e204125a8592ada8ab473dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":156,
              "y":465},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"297e7b2afed84d1f8cad35d37ab9d4a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":156,
                  "y":465},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8af8f52a85c342bd9f4fd5ff889c3235",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":53},
            "size":{
              "width":33,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c7220cad8ed4d558f78812ff628202d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":53},
                "size":{
                  "width":33,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"18601ce88a36415d9ecdc2b4f2b21608",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":60,
              "y":64},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9af1efac4b9c4ca78b4c3bf1814de48b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":60,
                  "y":64},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"77aabfcafec14ed580c7da910fb37e1f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":168,
              "y":110},
            "size":{
              "width":109,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe36ac048c914d5c8fd56d444a7faa5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":168,
                  "y":110},
                "size":{
                  "width":109,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户未拆红包或未塞满过期，24小时返回金额/u8.png"}},
{
          "id":"29495376221044268bf247d8488e63c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":180,
              "y":118},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2bd79e6946cb417ca5a24a8b6c316a94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":180,
                  "y":118},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2f31def2e55148dda4bd5992711c4fa1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":434},
            "size":{
              "width":270,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e87719c3b82475f909ded6892ec612b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":434},
                "size":{
                  "width":270,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"23fddfebd30d4098af0b38b56068b258",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":693,
              "y":210},
            "size":{
              "width":294,
              "height":300},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"14"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d2e370bebd54b59903d970f89dc3767",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":693,
                  "y":210},
                "size":{
                  "width":294,
                  "height":300},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"14"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户未拆红包或未塞满过期，24小时返回金额/u18.png"}},
{
          "id":"2bf3e80e3da2450582bc56d1926aa852",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":709,
              "y":231},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77ce90fe6800469fbc9bb781a6d0e1fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":709,
                  "y":231},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a0c798a4506a46f1bd72eab5eb1d05c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":709,
              "y":254},
            "size":{
              "width":50,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3ba650faa784415a528fb80fe28b6d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":709,
                  "y":254},
                "size":{
                  "width":50,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2c8081925698407eb8464196c2d0a9ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":709,
              "y":346},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"013577cc6c2745658746243b1062fbfa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":709,
                  "y":346},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2159a46783914c0c9886c4639f20cc01",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":709,
              "y":375},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5f1a60e87c249bfb76990704de5b54f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":709,
                  "y":375},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"94e821d030af43259042b6c7fc1e8ccb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":709,
              "y":406},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"daab487bd86a44a3ab4dec3968bd0b33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":709,
                  "y":406},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"21714b3ef2134fba9fa5121df5678f46",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":709,
              "y":467},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed10a8baa6fb42aab7c0abd0777b8f08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":709,
                  "y":467},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d8996cf8718c4f0aa724185378e3a6b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":775,
              "y":467},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd51a545aee5413a8e3cd8beeb4e9751",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":775,
                  "y":467},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"661c8836613b4eeb8ed8fd03b0500dc4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":709,
              "y":436},
            "size":{
              "width":301,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c6c0dc15df44143aa35496ec61fa85a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":709,
                  "y":436},
                "size":{
                  "width":301,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a512e27151324e249e04b4006a6b6745",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":410,
              "y":250},
            "size":{
              "width":210,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6c7ef73819a4c4bb002eb740bd4a842",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":410,
                  "y":250},
                "size":{
                  "width":210,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0b1b9aa375604ac28ee9419af5559e0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":410,
              "y":224},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01d0e056abf64bd5adc7e83bd9f5a1ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":410,
                  "y":224},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"644b10355a2948f1ad3e67038bc09fd1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":1030,
              "y":250},
            "size":{
              "width":200,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"255083090d4f4cea93fc2c894d3cef1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":1030,
                  "y":250},
                "size":{
                  "width":200,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bd5a038c040240c2b14d1f7effecc6ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":1030,
              "y":224},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dad1b2b8a7b046509bb1a9597c4dd9e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":1030,
                  "y":224},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7073e758edeb40ec8193d8d9885e6f52",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "verticalAlignment":"middle",
            "location":{
              "x":123,
              "y":290},
            "size":{
              "width":223,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3297fe72dd6140718deeb76a954b6333",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "verticalAlignment":"middle",
                "location":{
                  "x":123,
                  "y":290},
                "size":{
                  "width":223,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bb4b0b96052b4f63aaf89a3726302c7e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":324},
            "size":{
              "width":260,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/用户未拆红包或未塞满过期，24小时返回金额/u72_line.png"}},
{
          "id":"78198239d8a948199e1193738a99fc58",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "verticalAlignment":"middle",
            "location":{
              "x":740,
              "y":291},
            "size":{
              "width":196,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fbbb5b34aee4f7085fda2a5e7f03ab6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "verticalAlignment":"middle",
                "location":{
                  "x":740,
                  "y":291},
                "size":{
                  "width":196,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ee8c97de03747a9be0efd1e933eb893",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":709,
              "y":324},
            "size":{
              "width":260,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/用户未拆红包或未塞满过期，24小时返回金额/u72_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "df5c4212a9744144a2016e9fbf897a71":{
      "scriptId":"u0"},
    "f284cc7071d94d6d826f4a2038a9b153":{
      "scriptId":"u1"},
    "48f7f0d62c3e443c89659c9085ec8286":{
      "scriptId":"u2"},
    "2bb81627866b489fac4d75d797d52025":{
      "scriptId":"u3"},
    "6a16672b523c4d4eb8ee86d685c3c496":{
      "scriptId":"u4"},
    "0bf90456b26549e495e65fb9f15692d2":{
      "scriptId":"u5"},
    "b0042e409ac442009d08a2c379125990":{
      "scriptId":"u6"},
    "26a99cc7d1fd44e8b6267582e65283bb":{
      "scriptId":"u7"},
    "dbc035f9773f436d8bea5f0752abae7c":{
      "scriptId":"u8"},
    "1de9a5c1234f4c47b2b336881750fa73":{
      "scriptId":"u9"},
    "3dd0db31e60247a29d4431d32590426f":{
      "scriptId":"u10"},
    "ffd2db5f1d76464fa7aac04d6a42e0f0":{
      "scriptId":"u11"},
    "e52db3709bf147d3bcc7a9027896312c":{
      "scriptId":"u12"},
    "d13d8741ec864ba9947ca8519e9757cb":{
      "scriptId":"u13"},
    "3397d16800ad43bba8bce1cb9fe0230d":{
      "scriptId":"u14"},
    "b63da355ae194950a619427ee3d8af94":{
      "scriptId":"u15"},
    "d747245a99f74ca2ae8fea9fe3afdbb2":{
      "scriptId":"u16"},
    "5d41afc32bc34a739ae7af6600cd7a3f":{
      "scriptId":"u17"},
    "723398fdf0d34bc68931f4dcce807909":{
      "scriptId":"u18"},
    "99b71c13229d49ccba80e3a9754b82b1":{
      "scriptId":"u19"},
    "ac53fa83fe3243368b0c02afc1481882":{
      "scriptId":"u20"},
    "ea35118be435495692e062faa7aa6918":{
      "scriptId":"u21"},
    "79cc4899aa554587a9a3431147da9c71":{
      "scriptId":"u22"},
    "50c92869adc544b4946cfe9a7ad4acce":{
      "scriptId":"u23"},
    "c40fc06aeebd4993b28e359f7c2f3eb7":{
      "scriptId":"u24"},
    "bd3547fb094c48d4bb6dfdd9248b5082":{
      "scriptId":"u25"},
    "e2950009334643ab85d429b32a3fe73e":{
      "scriptId":"u26"},
    "a1a66088ec3449eaafddf569e8513884":{
      "scriptId":"u27"},
    "28d432572e314151b2606fe3cf3f5665":{
      "scriptId":"u28"},
    "b7821a2f75494643ad9a24f142b8c474":{
      "scriptId":"u29"},
    "2ae06a8515254cffaa9c34006832ecd3":{
      "scriptId":"u30"},
    "0ab58d1130664f388c627907161851cf":{
      "scriptId":"u31"},
    "ab7da1166e204125a8592ada8ab473dc":{
      "scriptId":"u32"},
    "297e7b2afed84d1f8cad35d37ab9d4a2":{
      "scriptId":"u33"},
    "8af8f52a85c342bd9f4fd5ff889c3235":{
      "scriptId":"u34"},
    "1c7220cad8ed4d558f78812ff628202d":{
      "scriptId":"u35"},
    "18601ce88a36415d9ecdc2b4f2b21608":{
      "scriptId":"u36"},
    "9af1efac4b9c4ca78b4c3bf1814de48b":{
      "scriptId":"u37"},
    "77aabfcafec14ed580c7da910fb37e1f":{
      "scriptId":"u38"},
    "fe36ac048c914d5c8fd56d444a7faa5e":{
      "scriptId":"u39"},
    "29495376221044268bf247d8488e63c0":{
      "scriptId":"u40"},
    "2bd79e6946cb417ca5a24a8b6c316a94":{
      "scriptId":"u41"},
    "2f31def2e55148dda4bd5992711c4fa1":{
      "scriptId":"u42"},
    "6e87719c3b82475f909ded6892ec612b":{
      "scriptId":"u43"},
    "23fddfebd30d4098af0b38b56068b258":{
      "scriptId":"u44"},
    "4d2e370bebd54b59903d970f89dc3767":{
      "scriptId":"u45"},
    "2bf3e80e3da2450582bc56d1926aa852":{
      "scriptId":"u46"},
    "77ce90fe6800469fbc9bb781a6d0e1fe":{
      "scriptId":"u47"},
    "a0c798a4506a46f1bd72eab5eb1d05c9":{
      "scriptId":"u48"},
    "d3ba650faa784415a528fb80fe28b6d6":{
      "scriptId":"u49"},
    "2c8081925698407eb8464196c2d0a9ed":{
      "scriptId":"u50"},
    "013577cc6c2745658746243b1062fbfa":{
      "scriptId":"u51"},
    "2159a46783914c0c9886c4639f20cc01":{
      "scriptId":"u52"},
    "c5f1a60e87c249bfb76990704de5b54f":{
      "scriptId":"u53"},
    "94e821d030af43259042b6c7fc1e8ccb":{
      "scriptId":"u54"},
    "daab487bd86a44a3ab4dec3968bd0b33":{
      "scriptId":"u55"},
    "21714b3ef2134fba9fa5121df5678f46":{
      "scriptId":"u56"},
    "ed10a8baa6fb42aab7c0abd0777b8f08":{
      "scriptId":"u57"},
    "d8996cf8718c4f0aa724185378e3a6b7":{
      "scriptId":"u58"},
    "dd51a545aee5413a8e3cd8beeb4e9751":{
      "scriptId":"u59"},
    "661c8836613b4eeb8ed8fd03b0500dc4":{
      "scriptId":"u60"},
    "0c6c0dc15df44143aa35496ec61fa85a":{
      "scriptId":"u61"},
    "a512e27151324e249e04b4006a6b6745":{
      "scriptId":"u62"},
    "e6c7ef73819a4c4bb002eb740bd4a842":{
      "scriptId":"u63"},
    "0b1b9aa375604ac28ee9419af5559e0f":{
      "scriptId":"u64"},
    "01d0e056abf64bd5adc7e83bd9f5a1ae":{
      "scriptId":"u65"},
    "644b10355a2948f1ad3e67038bc09fd1":{
      "scriptId":"u66"},
    "255083090d4f4cea93fc2c894d3cef1c":{
      "scriptId":"u67"},
    "bd5a038c040240c2b14d1f7effecc6ca":{
      "scriptId":"u68"},
    "dad1b2b8a7b046509bb1a9597c4dd9e4":{
      "scriptId":"u69"},
    "7073e758edeb40ec8193d8d9885e6f52":{
      "scriptId":"u70"},
    "3297fe72dd6140718deeb76a954b6333":{
      "scriptId":"u71"},
    "bb4b0b96052b4f63aaf89a3726302c7e":{
      "scriptId":"u72"},
    "78198239d8a948199e1193738a99fc58":{
      "scriptId":"u73"},
    "9fbbb5b34aee4f7085fda2a5e7f03ab6":{
      "scriptId":"u74"},
    "7ee8c97de03747a9be0efd1e933eb893":{
      "scriptId":"u75"}}});