$axure.loadCurrentPage({
  "url":"红包被拆完后，推送消息.html",
  "generationDate":new Date(1464855302654.42),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"31835c72aa1043e5ac1db25dc09e2a4f",
    "type":"Axure:Page",
    "name":"红包被拆完后，推送消息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f91f838048ef4787b71589be2035414b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":51},
            "size":{
              "width":320,
              "height":570},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c63b3d3014344fbbfb7bdaaa5cbe93c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":61,
                  "y":51},
                "size":{
                  "width":320,
                  "height":570},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】群会话入口/u24.png"}},
{
          "id":"6f1d23f1fa2c451b9737e5550b8113a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":61,
              "y":51},
            "size":{
              "width":320,
              "height":64},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2990cf008c0409c86a708c317cc0261",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":61,
                  "y":51},
                "size":{
                  "width":320,
                  "height":64},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】群会话入口/u26.png"}},
{
          "id":"27bfa7c3aaf2488eaebbb74d0bef19c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Helvetica CE Regular', 'Helvetica CE'",
            "fontSize":"12px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":71,
              "y":54},
            "size":{
              "width":86,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28e68f6ae86d455f9032ef8e0ee4db79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica CE Regular', 'Helvetica CE'",
                "fontSize":"12px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":71,
                  "y":54},
                "size":{
                  "width":86,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3468af8bb5d24e88ad6667578b7d705d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Helvetica CE Regular', 'Helvetica CE'",
            "fontSize":"12px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":205,
              "y":54},
            "size":{
              "width":32,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc9175c251064036a07c7eea1984e086",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica CE Regular', 'Helvetica CE'",
                "fontSize":"12px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":205,
                  "y":54},
                "size":{
                  "width":32,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6dc8c131fdc14ad4b73db829ffd438d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Helvetica CE Regular', 'Helvetica CE'",
            "fontSize":"12px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":321,
              "y":54},
            "size":{
              "width":26,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b64c34d033c426daf7ec51f1a7c1ecc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica CE Regular', 'Helvetica CE'",
                "fontSize":"12px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":321,
                  "y":54},
                "size":{
                  "width":26,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"727f61a11dbe42ae8e6b00e05c12c67e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":349,
              "y":54},
            "size":{
              "width":23,
              "height":14},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"482db5bc778f483fafddc61a987696a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":349,
                  "y":54},
                "size":{
                  "width":23,
                  "height":14},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】群会话入口/u34.png"}},
{
          "id":"b6083407727d4795b1547ec3af7f6fe5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":371,
              "y":56},
            "size":{
              "width":3,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88e33124902946e4a2165583d9cd09f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":371,
                  "y":56},
                "size":{
                  "width":3,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】群会话入口/u36.png"}},
{
          "id":"63f42b15e8204b7592dd6835385b0e40",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":349,
              "y":55},
            "size":{
              "width":18,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2072a40205c74bf2ab48443585f577b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":349,
                  "y":55},
                "size":{
                  "width":18,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】群会话入口/u38.png"}},
{
          "id":"623d4602bbc44d70aec59a5efc9ba240",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "location":{
              "x":146,
              "y":80},
            "size":{
              "width":145,
              "height":24},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88a87f498d7e4fe9a4520c1ac4673cc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "location":{
                  "x":146,
                  "y":80},
                "size":{
                  "width":145,
                  "height":24},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2ee3df9a05734299b69e6342cef2628e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":363},
            "size":{
              "width":320,
              "height":49},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8222bd7ec50f48edb8ea7cbae7e3e05f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":61,
                  "y":363},
                "size":{
                  "width":320,
                  "height":49},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】群会话入口/u42.png"}},
{
          "id":"cb46e6c7ca2e40c894f9af7dd6af0853",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":112,
              "y":369},
            "size":{
              "width":170,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0234812675a4586a40fa77a74f8afe5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":112,
                  "y":369},
                "size":{
                  "width":170,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】群会话入口/u44.png"}},
{
          "id":"271feef7d3304e34a56c4d358b9c9b9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":289,
              "y":368},
            "size":{
              "width":36,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a11eeef7c594f9a9d3fc48bcf0a8d5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":289,
                  "y":368},
                "size":{
                  "width":36,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】群会话入口/u46.png"}},
{
          "id":"cf984efffcf9477db721b00585bec27d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Narrow', 'Arial'",
            "fontSize":"30px",
            "location":{
              "x":335,
              "y":368},
            "size":{
              "width":36,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9e8ce2ff35241d599c88559a30d2ac5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Narrow', 'Arial'",
                "fontSize":"30px",
                "location":{
                  "x":335,
                  "y":368},
                "size":{
                  "width":36,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】群会话入口/u46.png"}},
{
          "id":"7d86e84a6f0b46a79aaed84e30cf6a55",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":368},
            "size":{
              "width":36,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16869fcade1a438cab3d3a46e356c1aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":368},
                "size":{
                  "width":36,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】群会话入口/u46.png"}},
{
          "id":"587d3b135d304555a3a9440188eb5f7b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":71,
              "y":82},
            "size":{
              "width":10,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52b3bde11bd746f99f565f1491e16ce2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":71,
                  "y":82},
                "size":{
                  "width":10,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】群会话入口/u52.png"}},
{
          "id":"37e3d707fd044aee8d0dbc5fe50c0c52",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":180},
            "size":{
              "width":33,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f8603f4051e42c79a7c5bbd6bea1000",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":180},
                "size":{
                  "width":33,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】群会话入口/u54.png"}},
{
          "id":"7e950a23a10c4f908d801287e4c335a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":122,
              "y":183},
            "size":{
              "width":90,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d04cfd7cda904524acde7bddd23b1372",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":122,
                  "y":183},
                "size":{
                  "width":90,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】群会话入口/u66.png"}},
{
          "id":"7cf35cb2acf544fa89736527d212f16c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":110,
              "y":175},
            "size":{
              "width":13,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e57b62c146e4b8d97991afd8ff4bd5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":110,
                  "y":175},
                "size":{
                  "width":13,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】群会话入口/u58.png"}},
{
          "id":"bdb47ae996c8452da7f9e572f38fb6d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":104,
              "y":175},
            "size":{
              "width":24,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2277d8806cf14051a052c04edfc6dd4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":104,
                  "y":175},
                "size":{
                  "width":24,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】群会话入口/u60.png"}},
{
          "id":"1bf71ae7fa80433b93aa875081db05f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":131,
              "y":187},
            "size":{
              "width":87,
              "height":20},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2dca6626fef04890b98e6adc08041824",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":131,
                  "y":187},
                "size":{
                  "width":87,
                  "height":20},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"34c2fc5288214aa0b71e44c5ff07bc25",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":338,
              "y":127},
            "size":{
              "width":33,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8e7168eb7b2404fa8fac2b213f21448",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":338,
                  "y":127},
                "size":{
                  "width":33,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】群会话入口/u54.png"}},
{
          "id":"0444b1e28bce497da75777f5625f84b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":273,
              "y":129},
            "size":{
              "width":45,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2cb0ec4761d64086941b806fb3dbd1c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":273,
                  "y":129},
                "size":{
                  "width":45,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】群会话入口/u76.png"}},
{
          "id":"36d1f7627a7c4a598de25cf1475e4312",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":317,
              "y":121},
            "size":{
              "width":13,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad579677a9b04254b87e856d7e261ef1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":317,
                  "y":121},
                "size":{
                  "width":13,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】群会话入口/u78.png"}},
{
          "id":"6fa644bada094714b006d5f3b3035e99",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":311,
              "y":121},
            "size":{
              "width":24,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00fd7eeb869b4f05babdd30e60fd04b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":311,
                  "y":121},
                "size":{
                  "width":24,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】群会话入口/u60.png"}},
{
          "id":"b03f9bf29e54423b9f3573ee8c7e3a9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":286,
              "y":133},
            "size":{
              "width":30,
              "height":20},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c358172c47a45eb9d962add6108d5a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":286,
                  "y":133},
                "size":{
                  "width":30,
                  "height":20},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e2b70b5c739c4b35961caa790508d610",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":195,
              "y":234},
            "size":{
              "width":50,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"24"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7bf07c2b8022433e9dca00fe5db7d8ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":195,
                  "y":234},
                "size":{
                  "width":50,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"24"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】群会话入口/u84.png"}},
{
          "id":"f25cd8dd95b746e89fcaa285cbed06df",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":78,
              "y":432},
            "size":{
              "width":52,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8dcf30fb33d54620aad93e8c1a384b75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":78,
                  "y":432},
                "size":{
                  "width":52,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】群会话入口/u86.png"}},
{
          "id":"0abd5da6f581409882bdc435fbffd7ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":155,
              "y":432},
            "size":{
              "width":52,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94a56545dd804c708eb877c1961f652b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":155,
                  "y":432},
                "size":{
                  "width":52,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】群会话入口/u86.png"}},
{
          "id":"01c653de89eb48a4954e760afe0cd179",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":233,
              "y":432},
            "size":{
              "width":52,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49454cd7ee5d488794ab5b82fb9e8fec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":233,
                  "y":432},
                "size":{
                  "width":52,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】群会话入口/u86.png"}},
{
          "id":"d1747961249f471a8114893a56d38330",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":432},
            "size":{
              "width":52,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd2cb42b758541df80aa87b62ddf0940",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":432},
                "size":{
                  "width":52,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】群会话入口/u86.png"}},
{
          "id":"a4a39c03a87c4013a761fc32c7a9d926",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "location":{
              "x":80,
              "y":489},
            "size":{
              "width":46,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a955c16a5e2d429382e671ef08fcad19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "location":{
                  "x":80,
                  "y":489},
                "size":{
                  "width":46,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8a4bf952b9104e1492b26a35bfb8dedb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "location":{
              "x":157,
              "y":489},
            "size":{
              "width":46,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b38375a855f3413d8bfc85ed8ce5c656",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "location":{
                  "x":157,
                  "y":489},
                "size":{
                  "width":46,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eee50ff8244045218c5238792ab6a2d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "location":{
              "x":234,
              "y":489},
            "size":{
              "width":46,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39443d9710e84cf79fc2944b99d35150",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "location":{
                  "x":234,
                  "y":489},
                "size":{
                  "width":46,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf639cf1ce0148e69fd262f5c14b7789",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "location":{
              "x":309,
              "y":489},
            "size":{
              "width":50,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46b423a7bf9941569e1f256d537402db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "location":{
                  "x":309,
                  "y":489},
                "size":{
                  "width":50,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"03074a3f575240a7b6e0f230d352646c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":78,
              "y":518},
            "size":{
              "width":52,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbe23b68cb904df097fff70cfb359c5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":78,
                  "y":518},
                "size":{
                  "width":52,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】群会话入口/u86.png"}},
{
          "id":"124c680c6d0c49b08e4574c1fd754165",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":155,
              "y":518},
            "size":{
              "width":52,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9c2a75c8c154efea378f4906bf9ab99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":155,
                  "y":518},
                "size":{
                  "width":52,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】群会话入口/u86.png"}},
{
          "id":"99baa9e0b2af47dcb8e7864ebf5f603b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":233,
              "y":518},
            "size":{
              "width":52,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82283c026829481f8f098aea66109cf0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":233,
                  "y":518},
                "size":{
                  "width":52,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】群会话入口/u86.png"}},
{
          "id":"bc1a46b77e84427298a848f02097a73c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":518},
            "size":{
              "width":52,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0e1e671a2dc4d7c8560b5181cac9296",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":518},
                "size":{
                  "width":52,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】群会话入口/u86.png"}},
{
          "id":"035c1d10b3f848d4aa4b729041ae7e30",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "location":{
              "x":78,
              "y":575},
            "size":{
              "width":48,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4d673059e3c438cba3933443204c5d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "location":{
                  "x":78,
                  "y":575},
                "size":{
                  "width":48,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"986e12888d01499286b3a8510f244bb4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "location":{
              "x":152,
              "y":575},
            "size":{
              "width":55,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"094cd965baa747dbbb7d2052e18bc3b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "location":{
                  "x":152,
                  "y":575},
                "size":{
                  "width":55,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5f0a7ee2941a4453b5cdb4db3fbafa9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "location":{
              "x":233,
              "y":575},
            "size":{
              "width":51,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8dd32348010446f8f3afbc75a3d6227",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "location":{
                  "x":233,
                  "y":575},
                "size":{
                  "width":51,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b3c44c837a6c4c86b2f02696389ee222",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "location":{
              "x":311,
              "y":575},
            "size":{
              "width":50,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92f923e082f0464aa065949d3f1f06d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "location":{
                  "x":311,
                  "y":575},
                "size":{
                  "width":50,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c0faf340454c4bee9e19b559078cb161",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":349,
              "y":84},
            "size":{
              "width":21,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"793548ec8c614c4c88037b49231bb1ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":349,
                  "y":84},
                "size":{
                  "width":21,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】群会话入口/u118.png"}},
{
          "id":"2fac3b821aa345c3bc8857481aa89306",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":296,
              "y":131},
            "size":{
              "width":72,
              "height":29},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"100",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":0,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0a06359ad4244e69a43e46e52cf9353",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":296,
                  "y":131},
                "size":{
                  "width":72,
                  "height":29},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"100",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":0,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】群会话入口/u120.png"}},
{
          "id":"e18e8b8f986049f0b68e70fd921f38de",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":304,
              "y":140},
            "size":{
              "width":13,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"397d0d7ebe344616b3d46f57e1c16082",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":304,
                  "y":140},
                "size":{
                  "width":13,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】群会话入口/u122.png"}},
{
          "id":"d9fdf15a878b44d997bc4d5449158644",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":270},
            "size":{
              "width":262,
              "height":70},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9cdf813908aa46b5b392724dc8306bf9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":270},
                "size":{
                  "width":262,
                  "height":70},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/推给发红包的用户/u90.png"}},
{
          "id":"fd3f2865714f4dada759d1db67dd792f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":282},
            "size":{
              "width":38,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc0f762e7b464c18ab027521ab42c8f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":282},
                "size":{
                  "width":38,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/推给发红包的用户/u92.png"}},
{
          "id":"b1cc097382ef433a83d497e218c5e008",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "location":{
              "x":146,
              "y":288},
            "size":{
              "width":192,
              "height":34},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f86428e3b6bf4c28b0aabc98ca6aa8b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "location":{
                  "x":146,
                  "y":288},
                "size":{
                  "width":192,
                  "height":34},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"76a3b78ab371491a9d2c1a6440769c4a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":61,
              "y":640},
            "size":{
              "width":317,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"543548f513494a459baf33ac1e182036",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":61,
                  "y":640},
                "size":{
                  "width":317,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"243f2654e0244a1ea6d93e3fe3cfdad5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":61,
              "y":728},
            "size":{
              "width":200,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdeff71d09b142d5a208ddc0a92ce880",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":61,
                  "y":728},
                "size":{
                  "width":200,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"478525b2d82e4e3cb8c5e54d19f0e34d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":61,
              "y":840},
            "size":{
              "width":200,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bffbb43654c4e13800cc451f3377e57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":61,
                  "y":840},
                "size":{
                  "width":200,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3c93d5c879ee492d9dcd91b271add2c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":865},
            "size":{
              "width":262,
              "height":70},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"254c5dc6113a45278e872b458eee0ec1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":61,
                  "y":865},
                "size":{
                  "width":262,
                  "height":70},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/推给发红包的用户/u90.png"}},
{
          "id":"d8856d4079b94753a36365757cda51db",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":71,
              "y":877},
            "size":{
              "width":38,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35bd05028b294e7a83d446f59630dedd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":71,
                  "y":877},
                "size":{
                  "width":38,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/推给发红包的用户/u92.png"}},
{
          "id":"edc0cfc522c942c88e6a88b25bac9552",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "location":{
              "x":117,
              "y":883},
            "size":{
              "width":192,
              "height":34},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63ca7aa6d6e744558c6b803f1342b358",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "location":{
                  "x":117,
                  "y":883},
                "size":{
                  "width":192,
                  "height":34},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"16edc4ea91ef4ce7a7b899466d990b08",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":61,
              "y":955},
            "size":{
              "width":200,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4922bde39ff4827a91bc798fa533c24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":61,
                  "y":955},
                "size":{
                  "width":200,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"977aa826548f4310b9ce702e5547a93b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":980},
            "size":{
              "width":262,
              "height":70},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae5f4f63aacc4d09b0d54110b78a0165",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":61,
                  "y":980},
                "size":{
                  "width":262,
                  "height":70},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/推给发红包的用户/u90.png"}},
{
          "id":"e6594e9e9036447ea063e7955b4e9e98",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":71,
              "y":992},
            "size":{
              "width":38,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"240fb1bd743a4672a36406e36a4738fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":71,
                  "y":992},
                "size":{
                  "width":38,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/推给发红包的用户/u92.png"}},
{
          "id":"f511ed66117745afbc6e5e03ca2d950b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "location":{
              "x":117,
              "y":998},
            "size":{
              "width":192,
              "height":34},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db55453249334505b03ceb9cbb34eebc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "location":{
                  "x":117,
                  "y":998},
                "size":{
                  "width":192,
                  "height":34},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"057a460d58d24c25a13dae1cdbc5e287",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":753},
            "size":{
              "width":262,
              "height":70},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58296f7ea75c40f3924cd8f848a92bc7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":61,
                  "y":753},
                "size":{
                  "width":262,
                  "height":70},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/推给发红包的用户/u90.png"}},
{
          "id":"78fc96d8c079432695062a8be5639976",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":71,
              "y":765},
            "size":{
              "width":38,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bfa3f9d9868477580522fccc14d823b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":71,
                  "y":765},
                "size":{
                  "width":38,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/推给发红包的用户/u92.png"}},
{
          "id":"6500b10f5b8e4280bcdeeb29e2d5609d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "location":{
              "x":117,
              "y":771},
            "size":{
              "width":192,
              "height":34},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1520fe51e2b24f4b8f2b518f7134e32c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "location":{
                  "x":117,
                  "y":771},
                "size":{
                  "width":192,
                  "height":34},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3544c41198e44b4f91dd2e15f2c248be",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":350,
              "y":765},
            "size":{
              "width":85,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"7"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1dc8dd86b93745379742dc9555ec1102",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":350,
                  "y":765},
                "size":{
                  "width":85,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"7"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/红包被拆完后，推送消息/u122.png"}},
{
          "id":"f5c7704222c3408d8a507a1580d08426",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "location":{
              "x":447,
              "y":767},
            "size":{
              "width":136,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50507062a26549d0ac3c28c631df0453",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "location":{
                  "x":447,
                  "y":767},
                "size":{
                  "width":136,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "f91f838048ef4787b71589be2035414b":{
      "scriptId":"u0"},
    "6c63b3d3014344fbbfb7bdaaa5cbe93c":{
      "scriptId":"u1"},
    "6f1d23f1fa2c451b9737e5550b8113a5":{
      "scriptId":"u2"},
    "b2990cf008c0409c86a708c317cc0261":{
      "scriptId":"u3"},
    "27bfa7c3aaf2488eaebbb74d0bef19c8":{
      "scriptId":"u4"},
    "28e68f6ae86d455f9032ef8e0ee4db79":{
      "scriptId":"u5"},
    "3468af8bb5d24e88ad6667578b7d705d":{
      "scriptId":"u6"},
    "dc9175c251064036a07c7eea1984e086":{
      "scriptId":"u7"},
    "6dc8c131fdc14ad4b73db829ffd438d9":{
      "scriptId":"u8"},
    "8b64c34d033c426daf7ec51f1a7c1ecc":{
      "scriptId":"u9"},
    "727f61a11dbe42ae8e6b00e05c12c67e":{
      "scriptId":"u10"},
    "482db5bc778f483fafddc61a987696a5":{
      "scriptId":"u11"},
    "b6083407727d4795b1547ec3af7f6fe5":{
      "scriptId":"u12"},
    "88e33124902946e4a2165583d9cd09f7":{
      "scriptId":"u13"},
    "63f42b15e8204b7592dd6835385b0e40":{
      "scriptId":"u14"},
    "2072a40205c74bf2ab48443585f577b5":{
      "scriptId":"u15"},
    "623d4602bbc44d70aec59a5efc9ba240":{
      "scriptId":"u16"},
    "88a87f498d7e4fe9a4520c1ac4673cc6":{
      "scriptId":"u17"},
    "2ee3df9a05734299b69e6342cef2628e":{
      "scriptId":"u18"},
    "8222bd7ec50f48edb8ea7cbae7e3e05f":{
      "scriptId":"u19"},
    "cb46e6c7ca2e40c894f9af7dd6af0853":{
      "scriptId":"u20"},
    "e0234812675a4586a40fa77a74f8afe5":{
      "scriptId":"u21"},
    "271feef7d3304e34a56c4d358b9c9b9f":{
      "scriptId":"u22"},
    "1a11eeef7c594f9a9d3fc48bcf0a8d5e":{
      "scriptId":"u23"},
    "cf984efffcf9477db721b00585bec27d":{
      "scriptId":"u24"},
    "c9e8ce2ff35241d599c88559a30d2ac5":{
      "scriptId":"u25"},
    "7d86e84a6f0b46a79aaed84e30cf6a55":{
      "scriptId":"u26"},
    "16869fcade1a438cab3d3a46e356c1aa":{
      "scriptId":"u27"},
    "587d3b135d304555a3a9440188eb5f7b":{
      "scriptId":"u28"},
    "52b3bde11bd746f99f565f1491e16ce2":{
      "scriptId":"u29"},
    "37e3d707fd044aee8d0dbc5fe50c0c52":{
      "scriptId":"u30"},
    "6f8603f4051e42c79a7c5bbd6bea1000":{
      "scriptId":"u31"},
    "7e950a23a10c4f908d801287e4c335a9":{
      "scriptId":"u32"},
    "d04cfd7cda904524acde7bddd23b1372":{
      "scriptId":"u33"},
    "7cf35cb2acf544fa89736527d212f16c":{
      "scriptId":"u34"},
    "8e57b62c146e4b8d97991afd8ff4bd5f":{
      "scriptId":"u35"},
    "bdb47ae996c8452da7f9e572f38fb6d2":{
      "scriptId":"u36"},
    "2277d8806cf14051a052c04edfc6dd4b":{
      "scriptId":"u37"},
    "1bf71ae7fa80433b93aa875081db05f3":{
      "scriptId":"u38"},
    "2dca6626fef04890b98e6adc08041824":{
      "scriptId":"u39"},
    "34c2fc5288214aa0b71e44c5ff07bc25":{
      "scriptId":"u40"},
    "c8e7168eb7b2404fa8fac2b213f21448":{
      "scriptId":"u41"},
    "0444b1e28bce497da75777f5625f84b5":{
      "scriptId":"u42"},
    "2cb0ec4761d64086941b806fb3dbd1c5":{
      "scriptId":"u43"},
    "36d1f7627a7c4a598de25cf1475e4312":{
      "scriptId":"u44"},
    "ad579677a9b04254b87e856d7e261ef1":{
      "scriptId":"u45"},
    "6fa644bada094714b006d5f3b3035e99":{
      "scriptId":"u46"},
    "00fd7eeb869b4f05babdd30e60fd04b5":{
      "scriptId":"u47"},
    "b03f9bf29e54423b9f3573ee8c7e3a9f":{
      "scriptId":"u48"},
    "7c358172c47a45eb9d962add6108d5a9":{
      "scriptId":"u49"},
    "e2b70b5c739c4b35961caa790508d610":{
      "scriptId":"u50"},
    "7bf07c2b8022433e9dca00fe5db7d8ce":{
      "scriptId":"u51"},
    "f25cd8dd95b746e89fcaa285cbed06df":{
      "scriptId":"u52"},
    "8dcf30fb33d54620aad93e8c1a384b75":{
      "scriptId":"u53"},
    "0abd5da6f581409882bdc435fbffd7ef":{
      "scriptId":"u54"},
    "94a56545dd804c708eb877c1961f652b":{
      "scriptId":"u55"},
    "01c653de89eb48a4954e760afe0cd179":{
      "scriptId":"u56"},
    "49454cd7ee5d488794ab5b82fb9e8fec":{
      "scriptId":"u57"},
    "d1747961249f471a8114893a56d38330":{
      "scriptId":"u58"},
    "cd2cb42b758541df80aa87b62ddf0940":{
      "scriptId":"u59"},
    "a4a39c03a87c4013a761fc32c7a9d926":{
      "scriptId":"u60"},
    "a955c16a5e2d429382e671ef08fcad19":{
      "scriptId":"u61"},
    "8a4bf952b9104e1492b26a35bfb8dedb":{
      "scriptId":"u62"},
    "b38375a855f3413d8bfc85ed8ce5c656":{
      "scriptId":"u63"},
    "eee50ff8244045218c5238792ab6a2d6":{
      "scriptId":"u64"},
    "39443d9710e84cf79fc2944b99d35150":{
      "scriptId":"u65"},
    "bf639cf1ce0148e69fd262f5c14b7789":{
      "scriptId":"u66"},
    "46b423a7bf9941569e1f256d537402db":{
      "scriptId":"u67"},
    "03074a3f575240a7b6e0f230d352646c":{
      "scriptId":"u68"},
    "fbe23b68cb904df097fff70cfb359c5b":{
      "scriptId":"u69"},
    "124c680c6d0c49b08e4574c1fd754165":{
      "scriptId":"u70"},
    "a9c2a75c8c154efea378f4906bf9ab99":{
      "scriptId":"u71"},
    "99baa9e0b2af47dcb8e7864ebf5f603b":{
      "scriptId":"u72"},
    "82283c026829481f8f098aea66109cf0":{
      "scriptId":"u73"},
    "bc1a46b77e84427298a848f02097a73c":{
      "scriptId":"u74"},
    "a0e1e671a2dc4d7c8560b5181cac9296":{
      "scriptId":"u75"},
    "035c1d10b3f848d4aa4b729041ae7e30":{
      "scriptId":"u76"},
    "d4d673059e3c438cba3933443204c5d7":{
      "scriptId":"u77"},
    "986e12888d01499286b3a8510f244bb4":{
      "scriptId":"u78"},
    "094cd965baa747dbbb7d2052e18bc3b8":{
      "scriptId":"u79"},
    "5f0a7ee2941a4453b5cdb4db3fbafa9c":{
      "scriptId":"u80"},
    "b8dd32348010446f8f3afbc75a3d6227":{
      "scriptId":"u81"},
    "b3c44c837a6c4c86b2f02696389ee222":{
      "scriptId":"u82"},
    "92f923e082f0464aa065949d3f1f06d6":{
      "scriptId":"u83"},
    "c0faf340454c4bee9e19b559078cb161":{
      "scriptId":"u84"},
    "793548ec8c614c4c88037b49231bb1ea":{
      "scriptId":"u85"},
    "2fac3b821aa345c3bc8857481aa89306":{
      "scriptId":"u86"},
    "d0a06359ad4244e69a43e46e52cf9353":{
      "scriptId":"u87"},
    "e18e8b8f986049f0b68e70fd921f38de":{
      "scriptId":"u88"},
    "397d0d7ebe344616b3d46f57e1c16082":{
      "scriptId":"u89"},
    "d9fdf15a878b44d997bc4d5449158644":{
      "scriptId":"u90"},
    "9cdf813908aa46b5b392724dc8306bf9":{
      "scriptId":"u91"},
    "fd3f2865714f4dada759d1db67dd792f":{
      "scriptId":"u92"},
    "bc0f762e7b464c18ab027521ab42c8f2":{
      "scriptId":"u93"},
    "b1cc097382ef433a83d497e218c5e008":{
      "scriptId":"u94"},
    "f86428e3b6bf4c28b0aabc98ca6aa8b1":{
      "scriptId":"u95"},
    "76a3b78ab371491a9d2c1a6440769c4a":{
      "scriptId":"u96"},
    "543548f513494a459baf33ac1e182036":{
      "scriptId":"u97"},
    "243f2654e0244a1ea6d93e3fe3cfdad5":{
      "scriptId":"u98"},
    "cdeff71d09b142d5a208ddc0a92ce880":{
      "scriptId":"u99"},
    "478525b2d82e4e3cb8c5e54d19f0e34d":{
      "scriptId":"u100"},
    "5bffbb43654c4e13800cc451f3377e57":{
      "scriptId":"u101"},
    "3c93d5c879ee492d9dcd91b271add2c7":{
      "scriptId":"u102"},
    "254c5dc6113a45278e872b458eee0ec1":{
      "scriptId":"u103"},
    "d8856d4079b94753a36365757cda51db":{
      "scriptId":"u104"},
    "35bd05028b294e7a83d446f59630dedd":{
      "scriptId":"u105"},
    "edc0cfc522c942c88e6a88b25bac9552":{
      "scriptId":"u106"},
    "63ca7aa6d6e744558c6b803f1342b358":{
      "scriptId":"u107"},
    "16edc4ea91ef4ce7a7b899466d990b08":{
      "scriptId":"u108"},
    "e4922bde39ff4827a91bc798fa533c24":{
      "scriptId":"u109"},
    "977aa826548f4310b9ce702e5547a93b":{
      "scriptId":"u110"},
    "ae5f4f63aacc4d09b0d54110b78a0165":{
      "scriptId":"u111"},
    "e6594e9e9036447ea063e7955b4e9e98":{
      "scriptId":"u112"},
    "240fb1bd743a4672a36406e36a4738fb":{
      "scriptId":"u113"},
    "f511ed66117745afbc6e5e03ca2d950b":{
      "scriptId":"u114"},
    "db55453249334505b03ceb9cbb34eebc":{
      "scriptId":"u115"},
    "057a460d58d24c25a13dae1cdbc5e287":{
      "scriptId":"u116"},
    "58296f7ea75c40f3924cd8f848a92bc7":{
      "scriptId":"u117"},
    "78fc96d8c079432695062a8be5639976":{
      "scriptId":"u118"},
    "4bfa3f9d9868477580522fccc14d823b":{
      "scriptId":"u119"},
    "6500b10f5b8e4280bcdeeb29e2d5609d":{
      "scriptId":"u120"},
    "1520fe51e2b24f4b8f2b518f7134e32c":{
      "scriptId":"u121"},
    "3544c41198e44b4f91dd2e15f2c248be":{
      "scriptId":"u122"},
    "1dc8dd86b93745379742dc9555ec1102":{
      "scriptId":"u123"},
    "f5c7704222c3408d8a507a1580d08426":{
      "scriptId":"u124"},
    "50507062a26549d0ac3c28c631df0453":{
      "scriptId":"u125"}}});