$axure.loadCurrentPage({
  "url":"因服务器定时处理，客户端需增加错误页面.html",
  "generationDate":new Date(1464855302284.38),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"18b21402a9324b30a4596095ca2fba26",
    "type":"Axure:Page",
    "name":"因服务器定时处理，客户端需增加错误页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"100fd08727974220aa42b1809546c576",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":90,
              "y":68},
            "size":{
              "width":320,
              "height":569},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c1e33a8f68a40219f79a10e03c226cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":90,
                  "y":68},
                "size":{
                  "width":320,
                  "height":569},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】点击消息体进入详情页_收到红包的人_/u0.png"}},
{
          "id":"bdeb09cd654c49fc85b3f9266d7ab467",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":90,
              "y":66},
            "size":{
              "width":320,
              "height":148},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d32585098d4d4faca00ff7eaaf6eefc0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":90,
                  "y":66},
                "size":{
                  "width":320,
                  "height":148},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】点击消息体进入详情页_收到红包的人_/u2.png"}},
{
          "id":"9b36b1213b8c4895823d609333e06167",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Helvetica CE Regular', 'Helvetica CE'",
            "fontSize":"12px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":100,
              "y":70},
            "size":{
              "width":86,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bd164fc5de541c19802ad4bde8f028a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica CE Regular', 'Helvetica CE'",
                "fontSize":"12px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":100,
                  "y":70},
                "size":{
                  "width":86,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"832a81c15f3347438fddfcb6a8108740",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Helvetica CE Regular', 'Helvetica CE'",
            "fontSize":"12px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":234,
              "y":70},
            "size":{
              "width":32,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"576ca0fda52a4f14b2ed485fd1c05a03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica CE Regular', 'Helvetica CE'",
                "fontSize":"12px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":234,
                  "y":70},
                "size":{
                  "width":32,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e5678799647a40b2b80ccda0db239c2c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Helvetica CE Regular', 'Helvetica CE'",
            "fontSize":"12px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":350,
              "y":70},
            "size":{
              "width":26,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7eb76b150294bab989b2b1f74c73003",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica CE Regular', 'Helvetica CE'",
                "fontSize":"12px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":350,
                  "y":70},
                "size":{
                  "width":26,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2f97c6f66fc7442ea622268100fee032",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":378,
              "y":70},
            "size":{
              "width":23,
              "height":14},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90d2b0cab8f1415dae9794590e773c72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":378,
                  "y":70},
                "size":{
                  "width":23,
                  "height":14},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】群会话入口/u34.png"}},
{
          "id":"0e8e9054244f46d58e86d91bf61ffb1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":400,
              "y":72},
            "size":{
              "width":3,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8ae68d5a64c4a298c24dae54812889d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":400,
                  "y":72},
                "size":{
                  "width":3,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】群会话入口/u36.png"}},
{
          "id":"1f36e5ee097147d98a7e4d3f8650cab8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "location":{
              "x":379,
              "y":70},
            "size":{
              "width":18,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9475e908f1047eea3c327520a4a1237",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "location":{
                  "x":379,
                  "y":70},
                "size":{
                  "width":18,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】群会话入口/u38.png"}},
{
          "id":"6a6d2d7f8647467399221ba36dc048ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"18px",
            "fontWeight":"200",
            "horizontalAlignment":"center",
            "location":{
              "x":178,
              "y":96},
            "size":{
              "width":145,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc06955fa8414e34be78152a232fe5c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"18px",
                "fontWeight":"200",
                "horizontalAlignment":"center",
                "location":{
                  "x":178,
                  "y":96},
                "size":{
                  "width":145,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0af22f9364ba4511b3903a3f891370e2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":93,
              "y":94},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a85359b60c544a2ebbee44a5829d423a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":93,
                  "y":94},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】群会话入口/u143.png"}},
{
          "id":"740ad3fa9b5c43bfa26835340db476ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":206},
            "size":{
              "width":320,
              "height":430},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc972662992e4032b4ff4fff9cd4e383",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":206},
                "size":{
                  "width":320,
                  "height":430},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】点击消息体进入详情页_收到红包的人_/u20.png"}},
{
          "id":"a84fbb567025461fb9654b1aaf9b0c0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":90,
              "y":164},
            "size":{
              "width":320,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea3c907c684041c2b4e05a95f7cfdf57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":90,
                  "y":164},
                "size":{
                  "width":320,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】点击消息体进入详情页_收到红包的人_/u26.png"}},
{
          "id":"bb7089c8f3074935833d8d5cd2a9f1f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":228,
              "y":130},
            "size":{
              "width":44,
              "height":44},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"029133de258a420694fb77433e5c29be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":228,
                  "y":130},
                "size":{
                  "width":44,
                  "height":44},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】点击消息体进入详情页_收到红包的人_/u28.png"}},
{
          "id":"33f685cae3e44e7190b252d4b83a670b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":119,
              "y":295},
            "size":{
              "width":261,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5a846de95f340d9b3bc4d2206601d97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":119,
                  "y":295},
                "size":{
                  "width":261,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"266446d893bd415f80a9617d658ceb92",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":164,
              "y":184},
            "size":{
              "width":174,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e7196ea19b541de9c3b1164cfe2b8e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":164,
                  "y":184},
                "size":{
                  "width":174,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"499fc4c04df34014998e7d38b461aa3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":151,
              "y":206},
            "size":{
              "width":200,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5fcee0f060bb468b949571243c4748de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":151,
                  "y":206},
                "size":{
                  "width":200,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7eab8bc01fe044d6b8e5d0dc4224c702",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":374},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/【2个页面需视觉设计】点击消息体进入详情页_收到红包的人_/u30_line.png"}},
{
          "id":"0b99d1527ddd4551a2ee6071631b214c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x66F2F2F2},
            "location":{
              "x":90,
              "y":379},
            "size":{
              "width":320,
              "height":26},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76167ae2bf324f9a9c6a187b4ba46eb0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x66F2F2F2},
                "location":{
                  "x":90,
                  "y":379},
                "size":{
                  "width":320,
                  "height":26},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】点击消息体进入详情页_收到红包的人_/u31.png"}},
{
          "id":"dd9a3997451d4975b355d9b6efbda849",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":104,
              "y":384},
            "size":{
              "width":186,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4ff1068e5d84d959c8e47e215c2ac77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":104,
                  "y":384},
                "size":{
                  "width":186,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab21ccc3be9042b3a6e1e9704b963d99",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":398},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/【2个页面需视觉设计】点击消息体进入详情页_收到红包的人_/u30_line.png"}},
{
          "id":"3d89c32afc2142aba32e9c93c076a00e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":404},
            "size":{
              "width":320,
              "height":66},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"878992aa99dd4c3ea444abbec815b9c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":404},
                "size":{
                  "width":320,
                  "height":66},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】点击消息体进入详情页_收到红包的人_/u36.png"}},
{
          "id":"0f9e7e89023e4675abb68ad96536c1a9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":525},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/【2个页面需视觉设计】点击消息体进入详情页_收到红包的人_/u30_line.png"}},
{
          "id":"7a48dba058e94c068d350b8c6cd4a8ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":104,
              "y":478},
            "size":{
              "width":40,
              "height":40},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f06e005b89444201ae169e12dbe468b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":104,
                  "y":478},
                "size":{
                  "width":40,
                  "height":40},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】点击消息体进入详情页_收到红包的人_/u39.png"}},
{
          "id":"241c8f2d394c4e39b658756e98c65c33",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":153,
              "y":479},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3cb850b4a51e45579566e8afeed65451",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":153,
                  "y":479},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1a0ad97903ab4bdca50b20e244b0e151",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":153,
              "y":500},
            "size":{
              "width":152,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"444fd687f48c4a38987d7dd3a3325796",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":153,
                  "y":500},
                "size":{
                  "width":152,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dff1027554b34cb8908fda74cc3b9e4c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":324,
              "y":479},
            "size":{
              "width":73,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0c216b9cb86486184e4c3b4dd64dcd0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":324,
                  "y":479},
                "size":{
                  "width":73,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d682df9fba64e61b79a8a1f9db035f2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":461},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/【2个页面需视觉设计】点击消息体进入详情页_收到红包的人_/u30_line.png"}},
{
          "id":"bd6741aede794864be3fa9a9b9257a46",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":104,
              "y":415},
            "size":{
              "width":40,
              "height":40},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3445274f9b2475d9f274a9696af99ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":104,
                  "y":415},
                "size":{
                  "width":40,
                  "height":40},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/【2个页面需视觉设计】点击消息体进入详情页_收到红包的人_/u39.png"}},
{
          "id":"1a460ecd37ce47b48397343f76b1a705",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":153,
              "y":415},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9224de53f0d34a17b797d9a2c5a1a0e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":153,
                  "y":415},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8adf6e8e25a14537b6460a5ae31a40eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":153,
              "y":437},
            "size":{
              "width":152,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7dcba4a1fc9455899a6ed093a495a29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":153,
                  "y":437},
                "size":{
                  "width":152,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"18fb235eb3574df9b02e74938470019b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":324,
              "y":418},
            "size":{
              "width":73,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2ba0ed035814681a90af4ab92b14663",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":324,
                  "y":418},
                "size":{
                  "width":73,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"72b9a6dce50f40f3a05b0bb25baff8f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":150,
              "y":325},
            "size":{
              "width":200,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15d17073a9564cf4bacfd9898cd7063a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":150,
                  "y":325},
                "size":{
                  "width":200,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e35e21d7af1a460a9ef0d18810a1b5cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":93,
              "y":657},
            "size":{
              "width":317,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc69deaedf47482a844f062cef50e685",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":93,
                  "y":657},
                "size":{
                  "width":317,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "100fd08727974220aa42b1809546c576":{
      "scriptId":"u0"},
    "2c1e33a8f68a40219f79a10e03c226cf":{
      "scriptId":"u1"},
    "bdeb09cd654c49fc85b3f9266d7ab467":{
      "scriptId":"u2"},
    "d32585098d4d4faca00ff7eaaf6eefc0":{
      "scriptId":"u3"},
    "9b36b1213b8c4895823d609333e06167":{
      "scriptId":"u4"},
    "5bd164fc5de541c19802ad4bde8f028a":{
      "scriptId":"u5"},
    "832a81c15f3347438fddfcb6a8108740":{
      "scriptId":"u6"},
    "576ca0fda52a4f14b2ed485fd1c05a03":{
      "scriptId":"u7"},
    "e5678799647a40b2b80ccda0db239c2c":{
      "scriptId":"u8"},
    "a7eb76b150294bab989b2b1f74c73003":{
      "scriptId":"u9"},
    "2f97c6f66fc7442ea622268100fee032":{
      "scriptId":"u10"},
    "90d2b0cab8f1415dae9794590e773c72":{
      "scriptId":"u11"},
    "0e8e9054244f46d58e86d91bf61ffb1b":{
      "scriptId":"u12"},
    "d8ae68d5a64c4a298c24dae54812889d":{
      "scriptId":"u13"},
    "1f36e5ee097147d98a7e4d3f8650cab8":{
      "scriptId":"u14"},
    "d9475e908f1047eea3c327520a4a1237":{
      "scriptId":"u15"},
    "6a6d2d7f8647467399221ba36dc048ca":{
      "scriptId":"u16"},
    "fc06955fa8414e34be78152a232fe5c5":{
      "scriptId":"u17"},
    "0af22f9364ba4511b3903a3f891370e2":{
      "scriptId":"u18"},
    "a85359b60c544a2ebbee44a5829d423a":{
      "scriptId":"u19"},
    "740ad3fa9b5c43bfa26835340db476ac":{
      "scriptId":"u20"},
    "bc972662992e4032b4ff4fff9cd4e383":{
      "scriptId":"u21"},
    "a84fbb567025461fb9654b1aaf9b0c0f":{
      "scriptId":"u22"},
    "ea3c907c684041c2b4e05a95f7cfdf57":{
      "scriptId":"u23"},
    "bb7089c8f3074935833d8d5cd2a9f1f4":{
      "scriptId":"u24"},
    "029133de258a420694fb77433e5c29be":{
      "scriptId":"u25"},
    "33f685cae3e44e7190b252d4b83a670b":{
      "scriptId":"u26"},
    "a5a846de95f340d9b3bc4d2206601d97":{
      "scriptId":"u27"},
    "266446d893bd415f80a9617d658ceb92":{
      "scriptId":"u28"},
    "5e7196ea19b541de9c3b1164cfe2b8e8":{
      "scriptId":"u29"},
    "499fc4c04df34014998e7d38b461aa3e":{
      "scriptId":"u30"},
    "5fcee0f060bb468b949571243c4748de":{
      "scriptId":"u31"},
    "7eab8bc01fe044d6b8e5d0dc4224c702":{
      "scriptId":"u32"},
    "0b99d1527ddd4551a2ee6071631b214c":{
      "scriptId":"u33"},
    "76167ae2bf324f9a9c6a187b4ba46eb0":{
      "scriptId":"u34"},
    "dd9a3997451d4975b355d9b6efbda849":{
      "scriptId":"u35"},
    "b4ff1068e5d84d959c8e47e215c2ac77":{
      "scriptId":"u36"},
    "ab21ccc3be9042b3a6e1e9704b963d99":{
      "scriptId":"u37"},
    "3d89c32afc2142aba32e9c93c076a00e":{
      "scriptId":"u38"},
    "878992aa99dd4c3ea444abbec815b9c6":{
      "scriptId":"u39"},
    "0f9e7e89023e4675abb68ad96536c1a9":{
      "scriptId":"u40"},
    "7a48dba058e94c068d350b8c6cd4a8ff":{
      "scriptId":"u41"},
    "f06e005b89444201ae169e12dbe468b7":{
      "scriptId":"u42"},
    "241c8f2d394c4e39b658756e98c65c33":{
      "scriptId":"u43"},
    "3cb850b4a51e45579566e8afeed65451":{
      "scriptId":"u44"},
    "1a0ad97903ab4bdca50b20e244b0e151":{
      "scriptId":"u45"},
    "444fd687f48c4a38987d7dd3a3325796":{
      "scriptId":"u46"},
    "dff1027554b34cb8908fda74cc3b9e4c":{
      "scriptId":"u47"},
    "d0c216b9cb86486184e4c3b4dd64dcd0":{
      "scriptId":"u48"},
    "8d682df9fba64e61b79a8a1f9db035f2":{
      "scriptId":"u49"},
    "bd6741aede794864be3fa9a9b9257a46":{
      "scriptId":"u50"},
    "b3445274f9b2475d9f274a9696af99ab":{
      "scriptId":"u51"},
    "1a460ecd37ce47b48397343f76b1a705":{
      "scriptId":"u52"},
    "9224de53f0d34a17b797d9a2c5a1a0e6":{
      "scriptId":"u53"},
    "8adf6e8e25a14537b6460a5ae31a40eb":{
      "scriptId":"u54"},
    "c7dcba4a1fc9455899a6ed093a495a29":{
      "scriptId":"u55"},
    "18fb235eb3574df9b02e74938470019b":{
      "scriptId":"u56"},
    "c2ba0ed035814681a90af4ab92b14663":{
      "scriptId":"u57"},
    "72b9a6dce50f40f3a05b0bb25baff8f6":{
      "scriptId":"u58"},
    "15d17073a9564cf4bacfd9898cd7063a":{
      "scriptId":"u59"},
    "e35e21d7af1a460a9ef0d18810a1b5cc":{
      "scriptId":"u60"},
    "bc69deaedf47482a844f062cef50e685":{
      "scriptId":"u61"}}});