$axure.loadCurrentPage({
  "url":"视觉设计要求和评分说明.html",
  "generationDate":new Date(1464855298039.95),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b9375e328a1c415f8f5b5a5d7ba56f0d",
    "type":"Axure:Page",
    "name":"视觉设计要求和评分说明",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"770da2be4a964333b7bb2154f4d3612b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":65,
              "y":51},
            "size":{
              "width":300,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16d059666ee74f3495d299e478dfc1b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":65,
                  "y":51},
                "size":{
                  "width":300,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"71200f83247240338b6d45ff11e6904f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":70},
            "size":{
              "width":985,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/众筹红包需求简介和更新记录/u2_line.png"}},
{
          "id":"f7503f707a3243198f95cc2cd25ccb32",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":65,
              "y":106},
            "size":{
              "width":353,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f95f41708add44b3909b45ed0680c6ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":65,
                  "y":106},
                "size":{
                  "width":353,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a9e534675514422a893567479a419c92",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":65,
              "y":176},
            "size":{
              "width":183,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7562444a5ff4ca09c110df6ff5ecc51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":65,
                  "y":176},
                "size":{
                  "width":183,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/视觉设计要求和评分说明/u5.png"}},
{
          "id":"0f6758a9bf984f3ab1e1bc93b1819334",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":245},
            "size":{
              "width":409,
              "height":165}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ac11786d7484d27887787087b71e5d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":65,
                  "y":245},
                "size":{
                  "width":409,
                  "height":165}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"02621d72051841f9ba764cb6908d1050",
                  "label":"",
                  "type":"hyperlink",
                  "styleType":"hyperlink",
                  "visible":true,
                  "style":{
                    "fontSize":"12px"},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 【2个页面需视觉设计】群会话入口",
                              "target":{
                                "targetType":"page",
                                "url":"【2个页面需视觉设计】群会话入口.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true},
{
                  "id":"c005c74219044601b7ec579aeeb3d54d",
                  "label":"",
                  "type":"hyperlink",
                  "styleType":"hyperlink",
                  "visible":true,
                  "style":{
                    "fontSize":"12px"},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 【2个页面需视觉设计】群会话入口",
                              "target":{
                                "targetType":"page",
                                "url":"【2个页面需视觉设计】群会话入口.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true},
{
                  "id":"a3394269a26a4a99a76ebe37deaf93eb",
                  "label":"",
                  "type":"hyperlink",
                  "styleType":"hyperlink",
                  "visible":true,
                  "style":{
                    "fontSize":"12px"},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 【1个页面需视觉设计】第一次进入创建页面或详情页面时的引导",
                              "target":{
                                "targetType":"page",
                                "url":"【1个页面需视觉设计】第一次进入创建页面或详情页面时的引导.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true},
{
                  "id":"70f817cd89fd42c2bedd8245e439bf49",
                  "label":"",
                  "type":"hyperlink",
                  "styleType":"hyperlink",
                  "visible":true,
                  "style":{
                    "fontSize":"12px"},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 【2个页面需视觉设计】点击消息体进入详情页(收到红包的人)",
                              "target":{
                                "targetType":"page",
                                "url":"【2个页面需视觉设计】点击消息体进入详情页_收到红包的人_.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true},
{
                  "id":"1401cede8eb14b8b812cb6350973c2cd",
                  "label":"",
                  "type":"hyperlink",
                  "styleType":"hyperlink",
                  "visible":true,
                  "style":{
                    "fontSize":"12px"},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 【2个页面需视觉设计】点击消息体进入详情页(收到红包的人)",
                              "target":{
                                "targetType":"page",
                                "url":"【2个页面需视觉设计】点击消息体进入详情页_收到红包的人_.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true}]}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dc843feade694f7d9e81e80406df6d90",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":65,
              "y":439},
            "size":{
              "width":353,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11b5d51434a94b60838e70d25644938c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":65,
                  "y":439},
                "size":{
                  "width":353,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"18d55dffcfce42adbbb90a3fdd576b68",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":65,
              "y":556},
            "size":{
              "width":353,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec14238d071d49aa95207795f640e02b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":65,
                  "y":556},
                "size":{
                  "width":353,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"00fa95a7c4a944eab99dbfb2f9aa9e87",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":65,
              "y":591},
            "size":{
              "width":628,
              "height":396},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"233c30ece48e4907afc7b354321495ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":65,
                  "y":591},
                "size":{
                  "width":628,
                  "height":396},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/视觉设计要求和评分说明/u18.png"}},
{
          "id":"86dbe38f6db04f8da307e5294fe862c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":65,
              "y":591},
            "size":{
              "width":628,
              "height":68},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad2ca7600bff44569ce7ed4d05691a98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":65,
                  "y":591},
                "size":{
                  "width":628,
                  "height":68},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/视觉设计要求和评分说明/u20.png"}},
{
          "id":"882af4c6eb2c4daf9b5f718bb1b39f73",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":65,
              "y":658},
            "size":{
              "width":94,
              "height":83},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84b317ba3769463faf227a59777221be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":65,
                  "y":658},
                "size":{
                  "width":94,
                  "height":83},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/视觉设计要求和评分说明/u22.png"}},
{
          "id":"9ac50d1685dd41ba9e318e65befa62ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":158,
              "y":591},
            "size":{
              "width":408,
              "height":68},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f2ef6b8188f46fbb25c9f01c884ce00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":158,
                  "y":591},
                "size":{
                  "width":408,
                  "height":68},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/视觉设计要求和评分说明/u24.png"}},
{
          "id":"3af537794bc541c6acded774b8a17912",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":565,
              "y":591},
            "size":{
              "width":128,
              "height":68},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78de2d4de5884c89a53e00614ea48edb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":565,
                  "y":591},
                "size":{
                  "width":128,
                  "height":68},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/视觉设计要求和评分说明/u26.png"}},
{
          "id":"240e7835facd4869acf18436460d2930",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":65,
              "y":740},
            "size":{
              "width":94,
              "height":83},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42617884b0654b2e9ffe44d07b43aef0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":65,
                  "y":740},
                "size":{
                  "width":94,
                  "height":83},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/视觉设计要求和评分说明/u22.png"}},
{
          "id":"f5b4af70e29e430d903726e7a0375293",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":65,
              "y":822},
            "size":{
              "width":94,
              "height":83},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70afd98e53724a76a619da5021645a10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":65,
                  "y":822},
                "size":{
                  "width":94,
                  "height":83},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/视觉设计要求和评分说明/u22.png"}},
{
          "id":"4e797e2fbe1044c9bb9834fc80516f92",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":65,
              "y":904},
            "size":{
              "width":94,
              "height":83},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"530b06fbe2e347518fe2c6ad0c8a8692",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":65,
                  "y":904},
                "size":{
                  "width":94,
                  "height":83},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/视觉设计要求和评分说明/u22.png"}},
{
          "id":"bb463340848942829240dd1896b7ed44",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":158,
              "y":658},
            "size":{
              "width":408,
              "height":83},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3eb14e81452940798341a51e262157fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":158,
                  "y":658},
                "size":{
                  "width":408,
                  "height":83},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/视觉设计要求和评分说明/u34.png"}},
{
          "id":"9827dcd918e84cdb9df4c5921ecee54d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":158,
              "y":740},
            "size":{
              "width":408,
              "height":83},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c1bdf06c81c4d8f889c61730c5ab4d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":158,
                  "y":740},
                "size":{
                  "width":408,
                  "height":83},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/视觉设计要求和评分说明/u34.png"}},
{
          "id":"78239d70ee9948398a4dda447b2f3807",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":158,
              "y":822},
            "size":{
              "width":408,
              "height":83},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b1f0ecbd45e45faa9f1fbf612dfcbdd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":158,
                  "y":822},
                "size":{
                  "width":408,
                  "height":83},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/视觉设计要求和评分说明/u34.png"}},
{
          "id":"c23d6ad23f584723a85f9b325a1ed26b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":158,
              "y":904},
            "size":{
              "width":408,
              "height":83},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e4e7260865f435ab3d9269ba44f863b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":158,
                  "y":904},
                "size":{
                  "width":408,
                  "height":83},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/视觉设计要求和评分说明/u34.png"}},
{
          "id":"79cc463ea4974f9c88e0f78988eff536",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":565,
              "y":658},
            "size":{
              "width":128,
              "height":83},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"175c3508409f432ea9a2a3acfdd3ffbe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":565,
                  "y":658},
                "size":{
                  "width":128,
                  "height":83},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/视觉设计要求和评分说明/u42.png"}},
{
          "id":"fa81fc9bc06d49e896af757fac060b17",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":565,
              "y":822},
            "size":{
              "width":128,
              "height":83},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd9b310f1e204fbd9a32089a1a229a97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":565,
                  "y":822},
                "size":{
                  "width":128,
                  "height":83},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/视觉设计要求和评分说明/u42.png"}},
{
          "id":"6e33d017dcc444278bd952e989f3b5dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":565,
              "y":740},
            "size":{
              "width":128,
              "height":83},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b3f14325e01456394b35726ec845dc4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":565,
                  "y":740},
                "size":{
                  "width":128,
                  "height":83},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/视觉设计要求和评分说明/u42.png"}},
{
          "id":"48120dd92b5141c1847b69b4d86324dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":565,
              "y":904},
            "size":{
              "width":128,
              "height":83},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f4c415a63484d6a8890114e4025dc7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":565,
                  "y":904},
                "size":{
                  "width":128,
                  "height":83},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/视觉设计要求和评分说明/u42.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "770da2be4a964333b7bb2154f4d3612b":{
      "scriptId":"u0"},
    "16d059666ee74f3495d299e478dfc1b2":{
      "scriptId":"u1"},
    "71200f83247240338b6d45ff11e6904f":{
      "scriptId":"u2"},
    "f7503f707a3243198f95cc2cd25ccb32":{
      "scriptId":"u3"},
    "f95f41708add44b3909b45ed0680c6ba":{
      "scriptId":"u4"},
    "a9e534675514422a893567479a419c92":{
      "scriptId":"u5"},
    "f7562444a5ff4ca09c110df6ff5ecc51":{
      "scriptId":"u6"},
    "0f6758a9bf984f3ab1e1bc93b1819334":{
      "scriptId":"u7"},
    "3ac11786d7484d27887787087b71e5d2":{
      "scriptId":"u8"},
    "02621d72051841f9ba764cb6908d1050":{
      "scriptId":"u9"},
    "c005c74219044601b7ec579aeeb3d54d":{
      "scriptId":"u10"},
    "a3394269a26a4a99a76ebe37deaf93eb":{
      "scriptId":"u11"},
    "70f817cd89fd42c2bedd8245e439bf49":{
      "scriptId":"u12"},
    "1401cede8eb14b8b812cb6350973c2cd":{
      "scriptId":"u13"},
    "dc843feade694f7d9e81e80406df6d90":{
      "scriptId":"u14"},
    "11b5d51434a94b60838e70d25644938c":{
      "scriptId":"u15"},
    "18d55dffcfce42adbbb90a3fdd576b68":{
      "scriptId":"u16"},
    "ec14238d071d49aa95207795f640e02b":{
      "scriptId":"u17"},
    "00fa95a7c4a944eab99dbfb2f9aa9e87":{
      "scriptId":"u18"},
    "233c30ece48e4907afc7b354321495ed":{
      "scriptId":"u19"},
    "86dbe38f6db04f8da307e5294fe862c7":{
      "scriptId":"u20"},
    "ad2ca7600bff44569ce7ed4d05691a98":{
      "scriptId":"u21"},
    "882af4c6eb2c4daf9b5f718bb1b39f73":{
      "scriptId":"u22"},
    "84b317ba3769463faf227a59777221be":{
      "scriptId":"u23"},
    "9ac50d1685dd41ba9e318e65befa62ad":{
      "scriptId":"u24"},
    "6f2ef6b8188f46fbb25c9f01c884ce00":{
      "scriptId":"u25"},
    "3af537794bc541c6acded774b8a17912":{
      "scriptId":"u26"},
    "78de2d4de5884c89a53e00614ea48edb":{
      "scriptId":"u27"},
    "240e7835facd4869acf18436460d2930":{
      "scriptId":"u28"},
    "42617884b0654b2e9ffe44d07b43aef0":{
      "scriptId":"u29"},
    "f5b4af70e29e430d903726e7a0375293":{
      "scriptId":"u30"},
    "70afd98e53724a76a619da5021645a10":{
      "scriptId":"u31"},
    "4e797e2fbe1044c9bb9834fc80516f92":{
      "scriptId":"u32"},
    "530b06fbe2e347518fe2c6ad0c8a8692":{
      "scriptId":"u33"},
    "bb463340848942829240dd1896b7ed44":{
      "scriptId":"u34"},
    "3eb14e81452940798341a51e262157fa":{
      "scriptId":"u35"},
    "9827dcd918e84cdb9df4c5921ecee54d":{
      "scriptId":"u36"},
    "3c1bdf06c81c4d8f889c61730c5ab4d4":{
      "scriptId":"u37"},
    "78239d70ee9948398a4dda447b2f3807":{
      "scriptId":"u38"},
    "3b1f0ecbd45e45faa9f1fbf612dfcbdd":{
      "scriptId":"u39"},
    "c23d6ad23f584723a85f9b325a1ed26b":{
      "scriptId":"u40"},
    "4e4e7260865f435ab3d9269ba44f863b":{
      "scriptId":"u41"},
    "79cc463ea4974f9c88e0f78988eff536":{
      "scriptId":"u42"},
    "175c3508409f432ea9a2a3acfdd3ffbe":{
      "scriptId":"u43"},
    "fa81fc9bc06d49e896af757fac060b17":{
      "scriptId":"u44"},
    "cd9b310f1e204fbd9a32089a1a229a97":{
      "scriptId":"u45"},
    "6e33d017dcc444278bd952e989f3b5dc":{
      "scriptId":"u46"},
    "9b3f14325e01456394b35726ec845dc4":{
      "scriptId":"u47"},
    "48120dd92b5141c1847b69b4d86324dd":{
      "scriptId":"u48"},
    "1f4c415a63484d6a8890114e4025dc7e":{
      "scriptId":"u49"}}});